### ISSUE TITLE
How to make labels from human?

### ISSUE THREAD

**Issue by CAI23sbP** [snu-mllab/DPPO#1]
@MountGuy 
I read your paper and code.
I want to get labels from human which is not synthetic labels.
But some codes are not working well.
e.g. `human_label_preprocess_*.py`

**Comment by MountGuy** [comment]
Thank you for your interest in our paper.

I think the source code is not perfectly refactored during the camera-ready phase.

We pushed the fixed version that contains index sampling step and label merging step.

Please try it and report again if it doesn't work.

**Comment by CAI23sbP** [comment]
@MountGuy Thank you for your reply.
By the way,  i have a single question about your project.
In your paper said that MDP components are <S, A, T, R, p0, H>, where H is a time horizon. H means that a fixed horizon?.
Or just slicing trajectories which were connected with the others to make segments ? 

Here is the fixed horizon [reference](https://imitation.readthedocs.io/en/latest/main-concepts/variable_horizon.html?highlight=fixed%20horizon)

**Comment by CAI23sbP** [comment]
@MountGuy Thank you for your reply. By the way, i have a single question about your project. In your paper said that MDP components are <S, A, T, R, p0, H>, where H is a time horizon. H means that a fixed horizon?(with a Absorbing state). Or just slicing trajectories which were connected with the others to make segments(without the absorbing state) ?
![Screenshot from 2024-07-22 17-56-32](https://github.com/user-attachments/assets/b394f000-d23e-497a-bb23-b5e8cd7edf5d)

Here is the fixed horizon [reference](https://imitation.readthedocs.io/en/latest/main-concepts/variable_horizon.html?highlight=fixed%20horizon)

**Comment by MountGuy** [comment]
Recall the robots of mujoco can go forward infinitely, so we mostly use halfcheetah, hopper, and walker a timeout termination. In our paper, a component H indicates this parameter and so the rollout process always ends after H steps.

**Comment by CAI23sbP** [comment]
@MountGuy Do you mean to only consider 'Truncation'?. i.e. terminate_when_unhealthy = False in a [refer](https://gymnasium.farama.org/main/environments/mujoco/hopper/#episode-end)

**Comment by MountGuy** [comment]
terminate_when_unhealthy option is True on our settings. However, even if we use that option, trained policy works very well so it goes forward infinitely without a timeout option. To summarize, our MDP is terminated by the either time horizon and unhealthy state.

**Comment by CAI23sbP** [comment]
Thank you!
