### ISSUE TITLE
A Question about your code

### ISSUE THREAD

**Issue by CAI23sbP** [snu-mllab/DPPO#2]
How have you been @MountGuy ?
I have a single question about your code.
The question:  what is a `self.seq_size` & `self.seq_len` ?
It is in a `dataset_utils.py` which is in a `JaxPref`.

```
        self.seq_observations = np.zeros((self.seq_size, self.seq_len, self.observations.shape[1]), np.float32)
        self.seq_actions = np.zeros((self.seq_size, self.seq_len, self.actions.shape[1]), np.float32)
        self.seq_rewards = np.zeros((self.seq_size, self.seq_len), np.float32) # to record true rewards
        self.seq_masks = np.zeros((self.seq_size, self.seq_len), np.float32)
        self.seq_timesteps = np.zeros((self.seq_size, self.seq_len), np.int32)

```

Here is my understanding
1. self.seq_size: traj_num * self.seq_len   
2. self.seq_len: a episode len (with fixed horizon)

Is it correct to think like this?

**Comment by MountGuy** [comment]
I am glad to see you again :)

The first step of our DPPO is to train a binary classifier that predicts human preferences.

Therefore, we have to use a dataset in which each element is a subtrajectory segment.

Here, self.seq_size is the size of the dataset, and self.seq_len is the length of a subtrajectory.

I hope this description to help you.

**Comment by CAI23sbP** [comment]
@MountGuy  
Thank you for a fast reply
